-- =============================================================================
--  CERRAR LA CUENTA Y EMPEZAR DE CERO
-- =============================================================================
--
--  Para qué: hasta ahora "la cuenta de los dos" se calculaba sumando desde el
--  primer día de la historia. Funciona, pero no se entiende: ves "te debe
--  450 €" y no sabes de dónde salen ni de cuándo. Y con los años obliga a la
--  app a repasar miles de apuntes cada vez.
--
--  Con esto, cuando quedáis en paz podéis poner una marca. A partir de ahí la
--  cuenta solo mira lo apuntado DESPUÉS de esa marca, y la app dice "desde el
--  cierre del 17 de septiembre" en vez de "desde el principio".
--
--  Solo se puede cerrar cuando el saldo está a cero, así que no se pierde
--  dinero de nadie: no hay nada que discutir y lo puede hacer cualquiera de
--  los dos.
--
--  Este archivo crea UNA tabla nueva. No toca ningún dato existente, no
--  cambia las reglas de privacidad de los apuntes y no borra nada.
--
--  Cómo se ejecuta: copiar todo y pegarlo en el Editor SQL de Supabase.
-- =============================================================================

-- 1. La tabla de cierres. Cada fila es un "hemos quedado en paz, a partir de
--    aquí empezamos de cero". Lo que importa es la fecha y hora.
create table if not exists public.cierres (
  id          bigint generated by default as identity primary key,
  quien       text,
  created_at  timestamptz not null default now()
);

-- 2. La misma protección que el resto de tablas de configuración: solo quien
--    ha entrado en la app. Un cierre no esconde nada, lo ven los dos.
alter table public.cierres enable row level security;

drop policy if exists "acceso autenticado" on public.cierres;
create policy "acceso autenticado" on public.cierres
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- 3. Comprobación: tiene que salir la tabla con sus tres columnas.
select column_name, data_type
from information_schema.columns
where table_schema = 'public' and table_name = 'cierres'
order by ordinal_position;

-- 4. Comprobación: tiene que dar 0. Todavía no hay ningún cierre, así que la
--    cuenta de los dos sigue calculándose igual que hasta ahora.
select count(*) as cierres_hechos from public.cierres;
