-- ============================================================
-- Gastos Cris y Adri — creación completa de la base de datos
-- Pegar entero en el Editor SQL de Supabase y pulsar "Run".
-- Es seguro ejecutarlo una sola vez sobre un proyecto vacío.
-- ============================================================

-- ------------------------------------------------------------
-- 1. TABLAS
-- ------------------------------------------------------------

create table if not exists public.eventos (
  id            bigint generated by default as identity primary key,
  nombre        text not null,
  fecha_inicio  date,
  fecha_fin     date,
  presupuesto   numeric,
  activo        boolean not null default false,
  archivado     boolean not null default false,
  created_at    timestamptz not null default now()
);

create table if not exists public.transacciones (
  id              bigint generated by default as identity primary key,
  fecha           date not null,
  importe         numeric not null,
  tipo            text not null check (tipo in ('gasto', 'ingreso')),
  categoria       text,
  subcategoria    text,
  establecimiento text,
  descripcion     text,
  medio_pago      text,
  quien           text,
  imagen_url      text,
  user_id         uuid references auth.users (id),
  evento_id       bigint references public.eventos (id) on delete set null,
  created_at      timestamptz not null default now()
);

create index if not exists transacciones_fecha_idx     on public.transacciones (fecha desc);
create index if not exists transacciones_evento_id_idx on public.transacciones (evento_id);

create table if not exists public.categorias (
  id         bigint generated by default as identity primary key,
  nombre     text not null,
  tipo       text not null check (tipo in ('gasto', 'ingreso')),
  padre_id   bigint references public.categorias (id) on delete cascade,
  orden      integer not null default 0,
  activa     boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists categorias_padre_id_idx on public.categorias (padre_id);

create table if not exists public.cuentas (
  id            bigint generated by default as identity primary key,
  nombre        text not null unique,
  emoji         text,
  saldo_inicial numeric not null default 0,
  created_at    timestamptz not null default now()
);

create table if not exists public.apuntes_recurrentes (
  id              bigint generated by default as identity primary key,
  nombre          text not null,
  importe         numeric not null,
  tipo            text not null check (tipo in ('gasto', 'ingreso')),
  categoria       text,
  subcategoria    text,
  establecimiento text,
  descripcion     text,
  medio_pago      text,
  dia_mes         integer not null default 1 check (dia_mes between 1 and 28),
  activo          boolean not null default true,
  created_at      timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 2. SEGURIDAD (RLS) — solo usuarios con sesión iniciada
-- ------------------------------------------------------------

alter table public.transacciones       enable row level security;
alter table public.categorias          enable row level security;
alter table public.cuentas             enable row level security;
alter table public.eventos             enable row level security;
alter table public.apuntes_recurrentes enable row level security;

drop policy if exists "acceso autenticado" on public.transacciones;
create policy "acceso autenticado" on public.transacciones
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "acceso autenticado" on public.categorias;
create policy "acceso autenticado" on public.categorias
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "acceso autenticado" on public.cuentas;
create policy "acceso autenticado" on public.cuentas
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "acceso autenticado" on public.eventos;
create policy "acceso autenticado" on public.eventos
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "acceso autenticado" on public.apuntes_recurrentes;
create policy "acceso autenticado" on public.apuntes_recurrentes
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- ------------------------------------------------------------
-- 3. CUENTAS DE PARTIDA (medios de pago)
-- ------------------------------------------------------------

insert into public.cuentas (nombre, emoji, saldo_inicial) values
  ('Efectivo Cris', '💵', 0),
  ('Efectivo Adri', '💵', 0),
  ('Tarjeta Cris',  '💳', 0),
  ('Tarjeta Adri',  '💳', 0),
  ('Banco',         '🏦', 0),
  ('Bizum',         '📱', 0),
  ('Transferencia', '🏦', 0),
  ('Tarjeta roja',  '💳', 0)
on conflict (nombre) do nothing;

-- ------------------------------------------------------------
-- 4. CATEGORÍAS DE PARTIDA
--    (luego se editan libremente desde Ajustes → Categorías)
-- ------------------------------------------------------------

do $$
declare
  v_padre bigint;
begin

  ----------------------------- GASTOS -----------------------------

  insert into public.categorias (nombre, tipo, orden) values ('Alimentación', 'gasto', 1) returning id into v_padre;
  insert into public.categorias (nombre, tipo, padre_id, orden) values
    ('Alcampo', 'gasto', v_padre, 0), ('Aldi', 'gasto', v_padre, 0),
    ('Bodegas El Pilar', 'gasto', v_padre, 0), ('BonArea', 'gasto', v_padre, 0),
    ('Carrefour', 'gasto', v_padre, 0), ('Erosky', 'gasto', v_padre, 0),
    ('Frutería', 'gasto', v_padre, 0), ('Hipercor', 'gasto', v_padre, 0),
    ('Lidl', 'gasto', v_padre, 0), ('Mercadona', 'gasto', v_padre, 0),
    ('Nespresso', 'gasto', v_padre, 0), ('Panadería', 'gasto', v_padre, 0),
    ('Pastelería', 'gasto', v_padre, 0), ('Toño Exclusivas Zaragoza', 'gasto', v_padre, 0);

  insert into public.categorias (nombre, tipo, orden) values ('Autopistas', 'gasto', 2);

  insert into public.categorias (nombre, tipo, orden) values ('Belleza', 'gasto', 3) returning id into v_padre;
  insert into public.categorias (nombre, tipo, padre_id, orden) values
    ('Cosméticos y colonias', 'gasto', v_padre, 0), ('Peluquería', 'gasto', v_padre, 0),
    ('Productos faciales', 'gasto', v_padre, 0);

  insert into public.categorias (nombre, tipo, orden) values ('Cultura', 'gasto', 4) returning id into v_padre;
  insert into public.categorias (nombre, tipo, padre_id, orden) values
    ('Espectáculos', 'gasto', v_padre, 0), ('Libros', 'gasto', v_padre, 0),
    ('Museos', 'gasto', v_padre, 0), ('Teatro', 'gasto', v_padre, 0);

  insert into public.categorias (nombre, tipo, orden) values ('Gastos Adri', 'gasto', 5);
  insert into public.categorias (nombre, tipo, orden) values ('Gastos Cris', 'gasto', 6);
  insert into public.categorias (nombre, tipo, orden) values ('Gastos varios o compensaciones', 'gasto', 7);

  insert into public.categorias (nombre, tipo, orden) values ('Hogar', 'gasto', 8) returning id into v_padre;
  insert into public.categorias (nombre, tipo, padre_id, orden) values
    ('Chino', 'gasto', v_padre, 0), ('Comunidad', 'gasto', v_padre, 0),
    ('IBI', 'gasto', v_padre, 0), ('Productos casa', 'gasto', v_padre, 0),
    ('Seguro hogar', 'gasto', v_padre, 0);

  insert into public.categorias (nombre, tipo, orden) values ('Inversión', 'gasto', 9);

  insert into public.categorias (nombre, tipo, orden) values ('Loterias', 'gasto', 10) returning id into v_padre;
  insert into public.categorias (nombre, tipo, padre_id, orden) values
    ('Cupones Once', 'gasto', v_padre, 0), ('Lotería Navidad', 'gasto', v_padre, 0),
    ('Primitiva', 'gasto', v_padre, 0);

  insert into public.categorias (nombre, tipo, orden) values ('Ocio', 'gasto', 11) returning id into v_padre;
  insert into public.categorias (nombre, tipo, padre_id, orden) values
    ('Baile', 'gasto', v_padre, 0), ('Bares-garitos', 'gasto', v_padre, 0),
    ('Cine', 'gasto', v_padre, 0), ('Frescano', 'gasto', v_padre, 0),
    ('Pastelería', 'gasto', v_padre, 0), ('Restaurantes', 'gasto', v_padre, 0),
    ('Taxis', 'gasto', v_padre, 0), ('Viajes', 'gasto', v_padre, 0);

  insert into public.categorias (nombre, tipo, orden) values ('Regalos', 'gasto', 12);

  insert into public.categorias (nombre, tipo, orden) values ('Ropa', 'gasto', 13) returning id into v_padre;
  insert into public.categorias (nombre, tipo, padre_id, orden) values
    ('Accesorios', 'gasto', v_padre, 0), ('Ropa', 'gasto', v_padre, 0),
    ('Snipes', 'gasto', v_padre, 0), ('Tintorería', 'gasto', v_padre, 0),
    ('Zapatos', 'gasto', v_padre, 0);

  insert into public.categorias (nombre, tipo, orden) values ('Salud', 'gasto', 14) returning id into v_padre;
  insert into public.categorias (nombre, tipo, padre_id, orden) values
    ('Dentista', 'gasto', v_padre, 0), ('Farmacia', 'gasto', v_padre, 0),
    ('Seguro DKV', 'gasto', v_padre, 0);

  insert into public.categorias (nombre, tipo, orden) values ('Suministros', 'gasto', 15) returning id into v_padre;
  insert into public.categorias (nombre, tipo, padre_id, orden) values
    ('Aguas y basuras', 'gasto', v_padre, 0), ('Apple', 'gasto', v_padre, 0),
    ('Arlo', 'gasto', v_padre, 0), ('Ecociudad', 'gasto', v_padre, 0),
    ('Gas', 'gasto', v_padre, 0), ('Impuesto agua ICA', 'gasto', v_padre, 0),
    ('Luz', 'gasto', v_padre, 0), ('Movistar', 'gasto', v_padre, 0),
    ('Netflix', 'gasto', v_padre, 0), ('Simyo', 'gasto', v_padre, 0),
    ('Spotify', 'gasto', v_padre, 0);

  insert into public.categorias (nombre, tipo, orden) values ('Transporte', 'gasto', 16) returning id into v_padre;
  insert into public.categorias (nombre, tipo, padre_id, orden) values
    ('Autobús y taxi', 'gasto', v_padre, 0);

  insert into public.categorias (nombre, tipo, orden) values ('Vehículos', 'gasto', 17) returning id into v_padre;
  insert into public.categorias (nombre, tipo, padre_id, orden) values
    ('Compra coche', 'gasto', v_padre, 0), ('Garaje', 'gasto', v_padre, 0),
    ('Gasolina', 'gasto', v_padre, 0), ('Impuesto Matriculación', 'gasto', v_padre, 0),
    ('Impuestos de circulación', 'gasto', v_padre, 0), ('ITV', 'gasto', v_padre, 0),
    ('Lavado', 'gasto', v_padre, 0), ('Parkings', 'gasto', v_padre, 0),
    ('Seguro', 'gasto', v_padre, 0), ('Taller', 'gasto', v_padre, 0);

  ---------------------------- INGRESOS ----------------------------

  insert into public.categorias (nombre, tipo, orden) values ('Bizum recibido', 'ingreso', 1);
  insert into public.categorias (nombre, tipo, orden) values ('Efectivo mensual', 'ingreso', 2);
  insert into public.categorias (nombre, tipo, orden) values ('Primer asiento', 'ingreso', 3);
  insert into public.categorias (nombre, tipo, orden) values ('Salario', 'ingreso', 4);
  insert into public.categorias (nombre, tipo, orden) values ('Tarjeta roja', 'ingreso', 5);

  insert into public.categorias (nombre, tipo, orden) values ('Varios', 'ingreso', 6) returning id into v_padre;
  insert into public.categorias (nombre, tipo, padre_id, orden) values
    ('Dinero extra', 'ingreso', v_padre, 0),
    ('Regularización por subida', 'ingreso', v_padre, 0),
    ('Varios efectivo', 'ingreso', v_padre, 0);

end $$;

-- Fin. El almacenamiento de las fotos de tickets se configura aparte,
-- con el script supabase-setup-storage.sql.
